version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    restart: unless-stopped
    depends_on:
      - db
    build: ./backend
    ports:
      - 8080:8080
    environment:
      DB_URL: db

  db:
    image: mysqldb
    ports:
      - 3307:3306
    environment:
      
      - MYSQL_DATABASE=miola
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=datamiola
      - MYSQL_PORT=3306
    